### ISSUE TITLE
tinker/user-overview returns 500 (Fatal error: Uncaught bunq\Exception\PleaseContactBunqException)

### ISSUE THREAD

**Issue by michelepatrassi** [bunq/tinker_php#32]
## Steps to reproduce:
1. `bash <(curl -s https://tinker.bunq.com/php/setup.sh)`
2. `tinker/user-overview.php `

## What should happen:
1. Should return an account, as describer in https://doc.bunq.com/#/android-emulator (Once installed, run tinker/user-overview, this will create an account for you when necessary)

## What happens: 
Returns a fatal error

## Traceback
[//]: # (If there is a traceback please share it in a quote! You can do this by pasting the traceback text, highlighting it and pressing the quote button.)

> Micheles-MacBook-Pro:tinker-php michele$  tinker/user-overview.php 
> *** tinkering cool logo ***
> Fatal error: Uncaught bunq\Exception\PleaseContactBunqException: HTTP Response Code: 500
> The response id to help bunq debug: The response header "X-Bunq-Client-Response-Id" or "x-bunq-client-response-id" could not be found.
> Error message: 
> 
> Encountered unhandled exception.
> 
>  in /Users/michele/dev/tmi/tinker-php/vendor/bunq/sdk_php/src/Exception/ExceptionFactory.php:64
> Stack trace:
> #0 /Users/michele/dev/tmi/tinker-php/vendor/bunq/sdk_php/src/Http/Handler/ResponseHandlerError.php(54): bunq\Exception\ExceptionFactory::createExceptionForResponse(Array, 500, 'The response he...')
> #1 /Users/michele/dev/tmi/tinker-php/vendor/bunq/sdk_php/src/Http/Handler/HandlerUtil.php(42): bunq\Http\Handler\ResponseHandlerError->execute(Object(GuzzleHttp\Psr7\Response))
> #2 /Users/michele/dev/tmi/tinker-php/vendor/guzzlehttp/promises/src/FulfilledPromise.php(39): bunq\Http\Handler\HandlerUtil::bunq\Http\Handler\{closure}(Object(GuzzleHttp\Psr7\Response))
> #3 /Users/michele/dev/tmi/tinker-php/vendor/guzzlehttp/p in /Users/michele/dev/tmi/tinker-php/vendor/bunq/sdk_php/src/Exception/ExceptionFactory.php on line 64

## SDK version and environment
- Tested on [0.10.0](https://github.com/bunq/sdk_php/releases/tag/0.10.0)
- [x] Sandbox
- [ ] Production

## Response id
[//]: # (If this error has something to do with a request that fails, please provide the response id of the request.)
- Response id: The response header "X-Bunq-Client-Response-Id" or "x-bunq-client-response-id" could not be found.

## Additional info
I just tried the java tinker and I successfully created an account, so it sounds like a problem for this SDK and not a server error

**Comment by basst85** [comment]
@Iar0  I've tried to simulate this error, but this error does not occurs on my machine

**Comment by OGKevin** [comment]
@Iar0 i think there is some stack trace missing? that cant be all right ? :P

**Comment by michelepatrassi** [comment]
@OGKevin I still had the terminal open, there was no more.

I tried to run the command again with a fresh folder and installation, now I get a different error:

> Fatal error: Uncaught bunq\Exception\BunqException: Generating a new private key failed. See "http://php.net/manual/en/function.openssl-pkey-new.php" for more info. in /Users/michele/dev/tmi/testphp/vendor/bunq/sdk_php/src/Security/KeyPair.php:66
> Stack trace:
> #0 /Users/michele/dev/tmi/testphp/vendor/bunq/sdk_php/src/Context/ApiContext.php(143): bunq\Security\KeyPair::generate()
> #1 [internal function]: bunq\Context\ApiContext->initializeInstallationContext()
> #2 /Users/michele/dev/tmi/testphp/vendor/bunq/sdk_php/src/Util/InstallationUtil.php(271): ReflectionMethod->invoke(Object(bunq\Context\ApiContext))
> #3 /Users/michele/dev/tmi/testphp/src/BunqLib.php(117): bunq\Util\InstallationUtil::automaticInstall(Object(bunq\Util\BunqEnumApiEnvironmentType), 'bunq-sandbox.co...')
> #4 /Users/michele/dev/tmi/testphp/src/BunqLib.php(99): bunq\tinker\BunqLib->setupContext()
> #5 /Users/michele/dev/tmi/testphp/tinker/user-overview.php(14): bunq\tinker\BunqLib->__construct(Object(bunq\Util\BunqEnumApiEnvironmentType))
> #6 {main}
>   thrown in /Users/michele/dev/tmi/testphp/vendor/bunq/sdk_php/src/Security/KeyPair.php on line 66

am I missing something?
