### ISSUE TITLE
Issue for PR #5, create option to make IBAN payments.

### ISSUE THREAD

**Issue by evharten** [bunq/tinker_php#6]
## Steps to reproduce:
1. make payment with IBAN

## What should happen:
1. process payment, normal makePayment function doesnt support IBAN (only Email and Phone)

## What happens:
1. with makePayment, it throws an error

## Traceback

```
 # PHP Fatal error:  Uncaught bunq\Exception\BadRequestException: HTTP Response Code: 400
The response id to help bunq debug: 6cbf9a52-7220-44d6-b118-2fb4d7458db5
Error message: Email has incorrect value "<IBAN>". in /home/evharten/betalingen/vendor/bunq/sdk_php/src/Exception/ExceptionFactory.php:52
Stack trace:
#0 /home/evharten/betalingen/vendor/bunq/sdk_php/src/Http/Handler/ResponseHandlerError.php(54): bunq\Exception\ExceptionFactory::createExceptionForResponse(Array, 400, '6cbf9a52-7220-4...')
#1 /home/evharten/betalingen/vendor/bunq/sdk_php/src/Http/Handler/HandlerUtil.php(42): bunq\Http\Handler\ResponseHandlerError->execute(Object(GuzzleHttp\Psr7\Response))
#2 /home/evharten/betalingen/vendor/guzzlehttp/promises/src/FulfilledPromise.php(39): bunq\Http\Handler\HandlerUtil::bunq\Http\Handler\{closure}(Object(GuzzleHttp\Psr7\Response))
#3 /home/evharten/betalingen/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\FulfilledPromise::GuzzleHttp\Promise\{closure}()
#4 /home/evharten/betalingen/vendo in /home/evharten/betalingen/vendor/bunq/sdk_php/src/Exception/ExceptionFactory.php on line 52
```

## SDK version and environment
- Tested on [0.12.4](https://github.com/bunq/sdk_php/releases/tag/0.12.4)
- [ ] Sandbox
- [X] Production

## Response id
[//]: # 
- Response id: 6cbf9a52-7220-44d6-b118-2fb4d7458db5

## Extra info:
 - Fixed in pullrequest #5

**Comment by OGKevin** [comment]
duplicate #7

**Comment by evharten** [comment]
#8 is for makeRequest, not makePayment ;) but the idea should be kinda the same.

**Comment by OGKevin** [comment]
#7 covers both, request inquiry and payment!

**Comment by evharten** [comment]
Ah yes i see now! good :)

**Comment by OGKevin** [comment]
Closing in favour of #7
